### ISSUE TITLE
Unable to receive/respond HTTP requests

### ISSUE THREAD

**Issue by canadaduane** [chef-js/uws#1]
A simple chef-uws server does not seem to be able to receive and respond to HTTP requests:

```ts
const server = await startServer({
  port: Number(process.env.PORT || 4200),
  join: "/join",
  leave: "/leave",
});

server.any("/*",  (res, req) => {
  res.writeStatus("200 OK").end("Hello!");
});
```

**Comment by Prozi** [comment]
@canadaduane strange this should work

since chef-js/socket such example works:

```
const startServer = require("chef-js/socket")

startServer.default().then((server) => {
    server.get("/*", (req, res) => {
      res.writeHead(200)
      res.end("Hello!")
    })
  }).catch(console.error)
```

**Comment by Prozi** [comment]
just replace `"/*"` with `"/whatever/*" you can't take the / route which is for the config.folder to have served index.html and other files from there

**Comment by Prozi** [comment]
please refer to https://github.com/chef-js/uws/issues/2#issuecomment-1605519799

**Comment by canadaduane** [comment]
Thanks for discovering the root cause! Perhaps there could be a warning to help others avoid surprise.

I'll give this a try soon (hopefully tomorrow).

**Comment by Prozi** [comment]
it is kind of specific to uws since they don't allow multiple route resolutions for same path, I think socket.io allows that but I'm not 100% sure

you could check chef-socket for a moment unless you prefer/need uws

best of luck!

**Comment by Prozi** [comment]
assuming it's working, please reopen if not, will add this to the readme sometime in near future
